settings = {
    'plugin.video.exodus': {
        'appearance.alt'        : '-',
        'appearance.1'          : 'Exodus',
        'scrapers.timeout.1'    : '30',
        'trakt.user'            : '',
        'indicators.alt'        : '1',
        'indicators'            : '0',
        'api.language'          : 'AUTO',
        'flatten.tvshows'       : 'false',
        'fanart'                : 'false', # default is 'true'
        'movie.widget'          : '1',
        'tv.widget.alt'         : '2',
        'tv.widget'             : '1',
        'lists.widget'          : '0', # default is '1'
        'trakt.user'            : '',
        'hosts.quality'         : '0',
        'hosts.mode'            : '1',
        'progress.dialog'       : '0',
        'hosts.captcha'         : 'false', # default is 'true'
        'hosts.sort.provider'   : 'false',
        'autoplay.sd'           : 'false',
        'bookmarks'             : 'true',
        'provider.primewire'    : 'true',
        'provider.movie25'      : 'true',
        'provider.watchseries'  : 'true',
        'provider.watchfree'    : 'true',
        'provider.directdl'     : 'true',
        'provider.ddlvalley'    : 'true',
        'provider.onemovies'    : 'true',
        'provider.ninemovies'   : 'true',
        'provider.pelispedia'   : 'true',
        'provider.putlocker'    : 'true',
        'provider.miradetodo'   : 'true',
        'provider.afdah'        : 'true',
        'provider.xmovies'      : 'true',
        'provider.pubfilm'      : 'true',
        'provider.tunemovie'    : 'true',
        'provider.sezonlukdizi' : 'true',
        'provider.dizilab'      : 'true',
        'provider.dizibox'      : 'true',
        'provider.onlinedizi'   : 'true',
        'provider.dizigold'     : 'true',
        'provider.einthusan'    : 'true',
        'provider.animeultima'  : 'true',
        'provider.torba'        : 'true',
        'provider.streamlord'   : 'true',
        'provider.moviesplanet' : 'true',
        'provider.ororo'        : 'true',
        'provider.library'      : 'true',
        'provider.dayt'         : 'true',
        'provider.genvideo'     : 'true',
        'provider.hevcfilm'     : 'true',
        'provider.movie4k'      : 'true',
        'provider.movieshd'     : 'true',
        'provider.newlinks'     : 'true',
        'provider.pftv'         : 'true',
        'provider.rainierland'  : 'true',
        'provider.releasebb'    : 'true',
        'provider.twoddl'       : 'true',
        'trakt.token'           : '',
        'trakt.refresh'         : '',
        'imdb.user'             : '',
        'moviesplanet.user'     : '',
        'moviesplanet.pass'     : '',
        'streamlord.user'       : '',
        'streamlord.pass'       : '',
        'ororo.user'            : '',
        'ororo.pass'            : '',
        'realdebrid.id'         : '',
        'realdebrid.secret'     : '',
        'realdebrid.token'      : '',
        'realdebrid.refresh'    : '',
        'premiumize.user'       : '',
        'premiumize.pin'        : '',
        'alldebrid.user'        : '',
        'alldebrid.pass'        : '',
        'rpnet.user'            : '',
        'rpnet.api'             : '',
        'downloads'             : 'false',
        'movie.download.path'   : '',
        'tv.download.path'      : '',
        'subtitles'             : 'false',
        'subtitles.utf'         : 'false',
        'subtitles.lang.1'      : 'English',
        'subtitles.lang.2'      : 'English'
    },
    'script.module.urlresolver': {
        'allow_universal'                      : 'true',
        'use_cache'                            : 'true',
        'AllDebridResolver_priority'           : '100',
        'AllDebridResolver_enabled'            : 'true',
        'AllDebridResolver_login'              : 'false',
        'AllDebridResolver_username'           : '',
        'AllDebridResolver_password'           : '',
        'PremiumizeMeResolver_priority'        : '100',
        'PremiumizeMeResolver_enabled'         : 'true',
        'PremiumizeMeResolver_use_https'       : 'false',
        'PremiumizeMeResolver_login'           : 'false',
        'PremiumizeMeResolver_username'        : '',
        'PremiumizeMeResolver_password'        : '',
        'RealDebridResolver_priority'          : '100',
        'RealDebridResolver_enabled'           : 'true',
        'RealDebridResolver_autopick'          : 'false',
        'RealDebridResolver_token'             : '',
        'RealDebridResolver_refresh'           : '',
        'RealDebridResolver_client_id'         : '',
        'RealDebridResolver_client_secret'     : '',
        'RPnetResolver_priority'               : '100',
        'RPnetResolver_enabled'                : 'true',
        'RPnetResolver_login'                  : 'false',
        'RPnetResolver_username'               : '',
        'RPnetResolver_password'               : '',
        'SimplyDebridResolver_priority'        : '100',
        'SimplyDebridResolver_enabled'         : 'true',
        'SimplyDebridResolver_login'           : 'false',
        'SimplyDebridResolver_username'        : '',
        'SimplyDebridResolver_password'        : '',
        'TwentyFourUploadingResolver_priority' : '100',
        'TwentyFourUploadingResolver_enabled'  : 'true',
        'AllmyvideosResolver_priority'         : '100',
        'AllmyvideosResolver_enabled'          : 'true',
        'AllVidResolver_priority'              : '100',
        'AllVidResolver_enabled'               : 'true',
        'AuEngineResolver_priority'            : '100',
        'AuEngineResolver_enabled'             : 'true',
        'BestreamsResolver_priority'           : '100',
        'BestreamsResolver_enabled'            : 'true',
        'CastampResolver_priority'             : '100',
        'CastampResolver_enabled'              : 'true',
        'ClickNUploadResolver_priority'        : '100',
        'ClickNUploadResolver_enabled'         : 'true',
        'CloudyResolver_priority'              : '100',
        'CloudyResolver_enabled'               : 'true',
        'CloudZillaResolver_priority'          : '100',
        'CloudZillaResolver_enabled'           : 'true',
        'CrunchyRollResolver_priority'         : '100',
        'CrunchyRollResolver_enabled'          : 'true',
        'DaclipsResolver_priority'             : '100',
        'DaclipsResolver_enabled'              : 'true',
        'DailymotionResolver_priority'         : '100',
        'DailymotionResolver_enabled'          : 'true',
        'DailymotionResolver_quality'          : '0',
        'DivxstageResolver_priority'           : '100',
        'DivxstageResolver_enabled'            : 'true',
        'EcostreamResolver_priority'           : '100',
        'EcostreamResolver_enabled'            : 'true',
        'ExashareResolver_priority'            : '100',
        'ExashareResolver_enabled'             : 'true',
        'FacebookResolver_priority'            : '100',
        'FacebookResolver_enabled'             : 'true',
        'FacebookResolver_quality'             : '0',
        'FilehootResolver_priority'            : '100',
        'FilehootResolver_enabled'             : 'true',
        'FilenukeResolver_priority'            : '100',
        'FilenukeResolver_enabled'             : 'true',
        'FilePupResolver_priority'             : '100',
        'FilePupResolver_enabled'              : 'true',
        'FilePupResolver_auto_pick'            : 'false',
        'FlashxResolver_priority'              : '100',
        'FlashxResolver_enabled'               : 'true',
        'FlashxResolver_auto_pick'             : 'false',
        'GoogleResolver_priority'              : '100',
        'GoogleResolver_enabled'               : 'true',
        'GoogleResolver_auto_pick'             : 'false',
        'GorillavidResolver_priority'          : '100',
        'GorillavidResolver_enabled'           : 'true',
        'GrifthostResolver_priority'           : '100',
        'GrifthostResolver_enabled'            : 'true',
        'HugefilesResolver_priority'           : '100',
        'HugefilesResolver_enabled'            : 'true',
        'IpithosResolver_priority'             : '100',
        'IpithosResolver_enabled'              : 'true',
        'IsharedResolver_priority'             : '100',
        'IsharedResolver_enabled'              : 'true',
        'KingFilesResolver_priority'           : '100',
        'KingFilesResolver_enabled'            : 'true',
        'LetwatchResolver_priority'            : '100',
        'LetwatchResolver_enabled'             : 'true',
        'MailRuResolver_priority'              : '100',
        'MailRuResolver_enabled'               : 'true',
        'MediaPlayBoxResolver_priority'        : '100',
        'MediaPlayBoxResolver_enabled'         : 'true',
        'MersalaResolver_priority'             : '100',
        'MersalaResolver_enabled'              : 'true',
        'MightyuploadResolver_priority'        : '100',
        'MightyuploadResolver_enabled'         : 'true',
        'MovDivxResolver_priority'             : '100',
        'MovDivxResolver_enabled'              : 'true',
        'MovpodResolver_priority'              : '100',
        'MovpodResolver_enabled'               : 'true',
        'MovshareResolver_priority'            : '100',
        'MovshareResolver_enabled'             : 'true',
        'Mp4EdgeResolver_priority'             : '100',
        'Mp4EdgeResolver_enabled'              : 'true',
        'Mp4streamResolver_priority'           : '100',
        'Mp4streamResolver_enabled'            : 'true',
        'Mp4uploadResolver_priority'           : '100',
        'Mp4uploadResolver_enabled'            : 'true',
        'NosvideoResolver_priority'            : '100',
        'NosvideoResolver_enabled'             : 'true',
        'NovamovResolver_priority'             : '100',
        'NovamovResolver_enabled'              : 'true',
        'NowvideoResolver_priority'            : '100',
        'NowvideoResolver_enabled'             : 'true',
        'OKResolver_priority'                  : '100',
        'OKResolver_enabled'                   : 'true',
        'OKResolver_auto_pick'                 : 'false',
        'OpenLoadResolver_priority'            : '100',
        'OpenLoadResolver_enabled'             : 'true',
        'Play44Resolver_priority'              : '100',
        'Play44Resolver_enabled'               : 'true',
        'PlayHDResolver_priority'              : '100',
        'PlayHDResolver_enabled'               : 'true',
        'PlaywireResolver_priority'            : '100',
        'PlaywireResolver_enabled'             : 'true',
        'PrimeshareResolver_priority'          : '100',
        'PrimeshareResolver_enabled'           : 'true',
        'PromptfileResolver_priority'          : '100',
        'PromptfileResolver_enabled'           : 'true',
        'PureVidResolver_priority'             : '100',
        'PureVidResolver_enabled'              : 'true',
        'PureVidResolver_login'                : 'false',
        'PureVidResolver_username'             : '',
        'PureVidResolver_password'             : '',
        'PureVidResolver_quality'              : 'Maximum',
        'Shared2meResolver_priority'           : '100',
        'Shared2meResolver_enabled'            : 'true',
        'SharedsxResolver_priority'            : '100',
        'SharedsxResolver_enabled'             : 'true',
        'SharerepoResolver_priority'           : '100',
        'SharerepoResolver_enabled'            : 'true',
        'SharesixResolver_priority'            : '100',
        'SharesixResolver_enabled'             : 'true',
        'SpeedPlayResolver_priority'           : '100',
        'SpeedPlayResolver_enabled'            : 'true',
        'SpeedVideoResolver_priority'          : '100',
        'SpeedVideoResolver_enabled'           : 'true',
        'StagevuResolver_priority'             : '100',
        'StagevuResolver_enabled'              : 'true',
        'StreamcloudResolver_priority'         : '100',
        'StreamcloudResolver_enabled'          : 'true',
        'StreamintoResolver_priority'          : '100',
        'StreamintoResolver_enabled'           : 'true',
        'TeramixerResolver_priority'           : '100',
        'TeramixerResolver_enabled'            : 'true',
        'TheVideoResolver_priority'            : '100',
        'TheVideoResolver_enabled'             : 'true',
        'VideoBeeResolver_priority'            : '100',
        'VideoBeeResolver_enabled'             : 'true',
        'TrollVidResolver_priority'            : '100',
        'TrollVidResolver_enabled'             : 'true',
        'TunePkResolver_priority'              : '100',
        'TunePkResolver_enabled'               : 'true',
        'TunePkResolver_quality'               : '0',
        'TusfilesResolver_priority'            : '100',
        'TusfilesResolver_enabled'             : 'true',
        'Up2StreamResolver_priority'           : '100',
        'Up2StreamResolver_enabled'            : 'true',
        'UploadAfResolver_priority'            : '100',
        'UploadAfResolver_enabled'             : 'true',
        'UploadcResolver_priority'             : '100',
        'UploadcResolver_enabled'              : 'true',
        'UploadXResolver_priority'             : '100',
        'UploadXResolver_enabled'              : 'true',
        'UpToBoxResolver_priority'             : '100',
        'UpToBoxResolver_enabled'              : 'true',
        'UsersCloudResolver_priority'          : '100',
        'UsersCloudResolver_enabled'           : 'true',
        'UsersFilesResolver_priority'          : '100',
        'UsersFilesResolver_enabled'           : 'true',
        'VeeHDResolver_priority'               : '100',
        'VeeHDResolver_enabled'                : 'true',
        'VeeHDResolver_login'                  : 'false',
        'VeeHDResolver_username'               : '',
        'VeeHDResolver_password'               : '',
        'VeohResolver_priority'                : '100',
        'VeohResolver_enabled'                 : 'true',
        'VidggResolver_priority'               : '100',
        'VidggResolver_enabled'                : 'true',
        'VidMeResolver_priority'               : '100',
        'VidMeResolver_enabled'                : 'true',
        'VidbullResolver_priority'             : '100',
        'VidbullResolver_enabled'              : 'true',
        'VidCrazyResolver_priority'            : '100',
        'VidCrazyResolver_enabled'             : 'true',
        'VideoHutResolver_priority'            : '100',
        'VideoHutResolver_enabled'             : 'true',
        'VideoMegaResolver_priority'           : '100',
        'VideoMegaResolver_enabled'            : 'true',
        'VideoRajResolver_priority'            : '100',
        'VideoRajResolver_enabled'             : 'true',
        'VideoTTResolver_priority'             : '100',
        'VideoTTResolver_enabled'              : 'true',
        'VideoTTResolver_quality'              : '0',
        'VideoweedResolver_priority'           : '100',
        'VideoweedResolver_enabled'            : 'true',
        'VideowoodResolver_priority'           : '100',
        'VideowoodResolver_enabled'            : 'true',
        'VideoZooResolver_priority'            : '100',
        'VideoZooResolver_enabled'             : 'true',
        'VidioResolver_priority'               : '100',
        'VidioResolver_enabled'                : 'true',
        'VidSpotResolver_priority'             : '100',
        'VidSpotResolver_enabled'              : 'true',
        'VidtoResolver_priority'               : '100',
        'VidtoResolver_enabled'                : 'true',
        'VidUpResolver_priority'               : '100',
        'VidUpResolver_enabled'                : 'true',
        'VidziResolver_priority'               : '100',
        'VidziResolver_enabled'                : 'true',
        'VimeoResolver_priority'               : '100',
        'VimeoResolver_enabled'                : 'true',
        'VimeoResolver_quality'                : '0',
        'VivosxResolver_priority'              : '100',
        'VivosxResolver_enabled'               : 'true',
        'VKResolver_priority'                  : '100',
        'VKResolver_enabled'                   : 'true',
        'VKResolver_auto_pick'                 : 'false',
        'VKPassResolver_priority'              : '100',
        'VKPassResolver_enabled'               : 'true',
        'VKPassResolver_auto_pick'             : 'false',
        'VodlockerResolver_priority'           : '100',
        'VodlockerResolver_enabled'            : 'true',
        'VshareResolver_priority'              : '100',
        'VshareResolver_enabled'               : 'true',
        'VshareEuResolver_priority'            : '100',
        'VshareEuResolver_enabled'             : 'true',
        'WatchVideoResolver_priority'          : '100',
        'WatchVideoResolver_enabled'           : 'true',
        'XvidstageResolver_priority'           : '100',
        'XvidstageResolver_enabled'            : 'true',
        'YourUploadResolver_priority'          : '100',
        'YourUploadResolver_enabled'           : 'true',
        'YoutubeResolver_priority'             : '100',
        'YoutubeResolver_enabled'              : 'true',
        'YouWatchResolver_priority'            : '100',
        'YouWatchResolver_enabled'             : 'true',
        'ZettahostResolver_priority'           : '100',
        'ZettahostResolver_enabled'            : 'true',
        'ZstreamResolver_priority'             : '100',
        'ZstreamResolver_enabled'              : 'true'
    }
}
strings = {
    'plugin.video.exodus': {
        32001: 'Movies',
        32002: 'TV Shows',
        32003: 'My Movies',
        32004: 'My TV Shows',
        32005: 'New Movies',
        32006: 'New Episodes',
        32007: 'Channels',
        32008: 'Tools',
        32009: 'Downloads',
        32010: 'Search',
        32011: 'Genres',
        32012: 'Year',
        32013: 'People',
        32014: 'Languages',
        32015: 'Certificates',
        32016: 'Networks',
        32017: 'People Watching',
        32018: 'Most Popular',
        32019: 'Most Voted',
        32020: 'Box Office',
        32021: 'Oscar Winners',
        32022: 'In Theaters',
        32023: 'Highly Rated',
        32024: 'Airing today',
        32025: 'Returning TV Shows',
        32026: 'New TV Shows',
        32027: 'TV Calendar',
        32028: 'People Search',
        32029: 'People (Movies)',
        32030: 'People (TV)',
        32031: 'Discover',
        32032: 'Collection',
        32033: 'Watchlist',
        32034: 'IMDb',
        32035: 'Featured',
        32036: 'History',
        32037: 'Progress',
        32038: 'Episodes',
        32039: 'Movie Lists',
        32040: 'TV Show Lists',
        32041: 'Episode Lists',
        32042: 'No Trakt or IMDb account found.',
        32043: '[B]SETTINGS[/B] : General',
        32044: '[B]SETTINGS[/B] : Accounts',
        32045: '[B]SETTINGS[/B] : Playback',
        32046: '[B]SETTINGS[/B] : Subtitles',
        32047: '[B]SETTINGS[/B] : Providers',
        32048: '[B]EXODUS[/B] : Downloads',
        32049: '[B]EXODUS[/B] : Viewtypes',
        32050: '[B]EXODUS[/B] : Clear providers...',
        32051: '[B]EXODUS[/B] : Clear metadata...',
        32052: '[B]EXODUS[/B] : Clear cache...',
        32053: '[I]Next Page[/I]',
        32054: 'Seasons',
        32055: 'Season',
        32056: 'Are you sure?',
        32057: 'Process Complete',
        32058: 'This will slow down things until they are re-cached!',
        32059: 'CLICK HERE TO SAVE VIEW',
        32060: 'January|February|March|April|May|June|July|August|September|October|November|December',
        32061: 'Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday',
        32062: '[B]%s[/B] : %s',
        32063: 'Play using...',
        32064: 'Auto Play',
        32065: 'Queue item',
        32066: 'Watched in Exodus',
        32067: 'Unwatched in Exodus',
        32068: 'Watched in Trakt',
        32069: 'Unwatched in Trakt',
        32070: 'Trakt Manager',
        32071: 'Browse Series',
        32072: 'Refresh',
        32301: 'Enabled',
        32302: 'Disabled',
        32303: 'User',
        32304: 'Email',
        32305: 'ID',
        32306: 'Authorization...',
        32307: 'Password',
        32308: 'PIN',
        32309: 'API',
        32310: 'General',
        32311: 'Appearance',
        32312: 'Providers Timeout',
        32313: 'Indicators',
        32314: 'Local',
        32315: 'Trakt',
        32316: 'Info Language',
        32317: 'Flatten TV seasons',
        32318: 'Enable Fanart',
        32319: 'Menu',
        32320: 'New Movies',
        32321: 'Featured',
        32322: 'People Watching',
        32323: 'Most Popular',
        32324: 'In Theaters',
        32325: 'New Episodes',
        32326: 'Episodes',
        32327: 'Trakt Progress',
        32328: 'Trakt Episodes',
        32329: 'My Lists',
        32330: 'Playback',
        32331: 'Default action',
        32332: 'Dialog',
        32333: 'Directory',
        32334: 'Auto Play',
        32335: 'Progress Dialog',
        32336: 'Foreground',
        32337: 'Background',
        32338: 'File Hosting Filters',
        32339: 'Max Quality',
        32340: 'SD Hosters in Auto Play',
        32341: 'Hosters with captchas',
        32342: 'Sort by Provider',
        32343: 'When playback starts...',
        32344: 'Resume Playback',
        32345: 'Providers',
        32346: 'Accounts',
        32347: 'Downloads',
        32348: 'Enable downloads',
        32349: 'Movies',
        32350: 'TV',
        32351: 'Downloading features are disabled by default.',
        32352: 'Set up your download folders in order to enable them.',
        32353: 'Subtitles',
        32354: 'Enable subtitles',
        32355: 'Convert subtitles to UTF-8',
        32356: 'Primary Language',
        32357: 'Secondary Language',
        32358: 'Subtitles could be unavailable or out of sync.',
        32359: 'In that case use your own subtitles.',
        32401: 'No stream available',
        32402: 'Playback outside Exodus is not allowed',
        32403: 'Download',
        32404: 'Time elapsed: %s seconds',
        32405: '%s seconds',
        32406: 'Remaining providers: %s',
        32407: 'Are you sure?',
        32408: 'Process Complete',
        32501: 'Start from beginning',
        32502: 'Resume from %s',
        32503: 'Resume',
        32511: 'An account already exists.',
        32512: 'Do you want to reset?',
        32513: '1) Visit : [COLOR skyblue]%s[/COLOR]',
        32514: '2) When prompted enter : [COLOR skyblue]%s[/COLOR]',
        32515: 'Trakt Manager',
        32516: 'Add to [B]Collection[/B]',
        32517: 'Remove from [B]Collection[/B]',
        32518: 'Add to [B]Watchlist[/B]',
        32519: 'Remove from [B]Watchlist[/B]',
        32520: 'Add to [B]new List[/B]',
        32521: 'Add to [B]%s[/B]',
        32522: 'Remove from [B]%s[/B]',
        32531: 'An account already exists.',
        32532: 'Do you want to reset?',
        32533: '1) Visit : [COLOR skyblue]%s[/COLOR]',
        32534: '2) When prompted enter : [COLOR skyblue]%s[/COLOR]'
    }
}
