settings = {
    'plugin.video.exodus': {
        'appearance.alt'        : '-',
        'appearance.1'          : 'Exodus',
        'scrapers.timeout.1'    : '30',
        'trakt.user'            : '',
        'indicators.alt'        : '0',
        'indicators'            : '0',
        'api.language'          : 'AUTO',
        'flatten.tvshows'       : 'false',
        'fanart'                : 'false', # default is 'true'
        'movie.widget'          : '1',
        'tv.widget.alt'         : '2',
        'tv.widget'             : '1',
        'calendar.widget'       : '0',
        'lists.widget'          : '0', # default is '1'
        'trakt.user'            : '',
        'imdb.user'             : '',
        'menu.classic'          : 'true',
        'hosts.quality'         : '0',
        'hosts.mode'            : '1',
        'progress.dialog'       : '0',
        'hosts.captcha'         : 'false', # default is 'true'
        'hosts.sort.provider'   : 'false',
        'autoplay'              : 'false',
        'autoplay.sd'           : 'false',
        'bookmarks'             : 'true',
        'player.info'           : 'false',
        'provider.primewire'    : 'true',
        'provider.movie25'      : 'true',
        'provider.watchseries'  : 'true',
        'provider.watchfree'    : 'true',
        'provider.directdl'     : 'true',
        'provider.ddlvalley'    : 'true',
        'provider.mvlinks'      : 'true',
        'provider.watch1080'    : 'true',
        'provider.onemovies'    : 'true',
        'provider.ninemovies'   : 'true',
        'provider.pelispedia'   : 'true',
        'provider.putlocker'    : 'true',
        'provider.miradetodo'   : 'true',
        'provider.usmovies'     : 'true',
        'provider.usseries'     : 'true',
        'provider.afdah'        : 'true',
        'provider.xmovies'      : 'true',
        'provider.pubfilm'      : 'true',
        'provider.tunemovie'    : 'true',
        'provider.sezonlukdizi' : 'true',
        'provider.dizilab'      : 'true',
        'provider.dizibox'      : 'true',
        'provider.onlinedizi'   : 'true',
        'provider.dizigold'     : 'true',
        'provider.einthusan'    : 'true',
        'provider.animeultima'  : 'true',
        'provider.torba'        : 'true',
        'provider.streamlord'   : 'true',
        'provider.moviestorm'   : 'true',
        'provider.moviesplanet' : 'true',
        'provider.ororo'        : 'true',
        'provider.library'      : 'true',
        'trakt.token'           : '',
        'trakt.refresh'         : '',
        'imdb.user'             : '',
        'moviesplanet.user'     : '',
        'moviesplanet.pass'     : '',
        'streamlord.user'       : '',
        'streamlord.pass'       : '',
        'ororo.user'            : '',
        'ororo.pass'            : '',
        'realdebrid.id'         : '',
        'realdebrid.secret'     : '',
        'realdebrid.token'      : '',
        'realdebrid.refresh'    : '',
        'premiumize.user'       : '',
        'premiumize.pin'        : '',
        'alldebrid.user'        : '',
        'alldebrid.pass'        : '',
        'rpnet.user'            : '',
        'rpnet.api'             : '',
        'downloads'             : 'false',
        'movie.download.path'   : '',
        'tv.download.path'      : '',
        'subtitles'             : 'false',
        'subtitles.utf'         : 'false',
        'subtitles.lang.1'      : 'English',
        'subtitles.lang.2'      : 'English'
    },
    'script.module.urlresolver': {
        'allow_universal'                      : 'true',
        'use_cache'                            : 'true',
        'AllDebridResolver_priority'           : '100',
        'AllDebridResolver_enabled'            : 'true',
        'AllDebridResolver_login'              : 'false',
        'AllDebridResolver_username'           : '',
        'AllDebridResolver_password'           : '',
        'PremiumizeMeResolver_priority'        : '100',
        'PremiumizeMeResolver_enabled'         : 'true',
        'PremiumizeMeResolver_use_https'       : 'false',
        'PremiumizeMeResolver_login'           : 'false',
        'PremiumizeMeResolver_username'        : '',
        'PremiumizeMeResolver_password'        : '',
        'RealDebridResolver_priority'          : '100',
        'RealDebridResolver_enabled'           : 'true',
        'RealDebridResolver_autopick'          : 'false',
        'RealDebridResolver_token'             : '',
        'RealDebridResolver_refresh'           : '',
        'RealDebridResolver_client_id'         : '',
        'RealDebridResolver_client_secret'     : '',
        'RPnetResolver_priority'               : '100',
        'RPnetResolver_enabled'                : 'true',
        'RPnetResolver_login'                  : 'false',
        'RPnetResolver_username'               : '',
        'RPnetResolver_password'               : '',
        'SimplyDebridResolver_priority'        : '100',
        'SimplyDebridResolver_enabled'         : 'true',
        'SimplyDebridResolver_login'           : 'false',
        'SimplyDebridResolver_username'        : '',
        'SimplyDebridResolver_password'        : '',
        'TwentyFourUploadingResolver_priority' : '100',
        'TwentyFourUploadingResolver_enabled'  : 'true',
        'AllmyvideosResolver_priority'         : '100',
        'AllmyvideosResolver_enabled'          : 'true',
        'AllVidResolver_priority'              : '100',
        'AllVidResolver_enabled'               : 'true',
        'AuEngineResolver_priority'            : '100',
        'AuEngineResolver_enabled'             : 'true',
        'BestreamsResolver_priority'           : '100',
        'BestreamsResolver_enabled'            : 'true',
        'CastampResolver_priority'             : '100',
        'CastampResolver_enabled'              : 'true',
        'ClickNUploadResolver_priority'        : '100',
        'ClickNUploadResolver_enabled'         : 'true',
        'CloudyResolver_priority'              : '100',
        'CloudyResolver_enabled'               : 'true',
        'CloudZillaResolver_priority'          : '100',
        'CloudZillaResolver_enabled'           : 'true',
        'CrunchyRollResolver_priority'         : '100',
        'CrunchyRollResolver_enabled'          : 'true',
        'DaclipsResolver_priority'             : '100',
        'DaclipsResolver_enabled'              : 'true',
        'DailymotionResolver_priority'         : '100',
        'DailymotionResolver_enabled'          : 'true',
        'DailymotionResolver_quality'          : '0',
        'DivxstageResolver_priority'           : '100',
        'DivxstageResolver_enabled'            : 'true',
        'EcostreamResolver_priority'           : '100',
        'EcostreamResolver_enabled'            : 'true',
        'ExashareResolver_priority'            : '100',
        'ExashareResolver_enabled'             : 'true',
        'FacebookResolver_priority'            : '100',
        'FacebookResolver_enabled'             : 'true',
        'FacebookResolver_quality'             : '0',
        'FilehootResolver_priority'            : '100',
        'FilehootResolver_enabled'             : 'true',
        'FilenukeResolver_priority'            : '100',
        'FilenukeResolver_enabled'             : 'true',
        'FilePupResolver_priority'             : '100',
        'FilePupResolver_enabled'              : 'true',
        'FilePupResolver_auto_pick'            : 'false',
        'FlashxResolver_priority'              : '100',
        'FlashxResolver_enabled'               : 'true',
        'FlashxResolver_auto_pick'             : 'false',
        'GoogleResolver_priority'              : '100',
        'GoogleResolver_enabled'               : 'true',
        'GoogleResolver_auto_pick'             : 'false',
        'GorillavidResolver_priority'          : '100',
        'GorillavidResolver_enabled'           : 'true',
        'GrifthostResolver_priority'           : '100',
        'GrifthostResolver_enabled'            : 'true',
        'HugefilesResolver_priority'           : '100',
        'HugefilesResolver_enabled'            : 'true',
        'IpithosResolver_priority'             : '100',
        'IpithosResolver_enabled'              : 'true',
        'IsharedResolver_priority'             : '100',
        'IsharedResolver_enabled'              : 'true',
        'KingFilesResolver_priority'           : '100',
        'KingFilesResolver_enabled'            : 'true',
        'LetwatchResolver_priority'            : '100',
        'LetwatchResolver_enabled'             : 'true',
        'MailRuResolver_priority'              : '100',
        'MailRuResolver_enabled'               : 'true',
        'MediaPlayBoxResolver_priority'        : '100',
        'MediaPlayBoxResolver_enabled'         : 'true',
        'MersalaResolver_priority'             : '100',
        'MersalaResolver_enabled'              : 'true',
        'MightyuploadResolver_priority'        : '100',
        'MightyuploadResolver_enabled'         : 'true',
        'MovDivxResolver_priority'             : '100',
        'MovDivxResolver_enabled'              : 'true',
        'MovpodResolver_priority'              : '100',
        'MovpodResolver_enabled'               : 'true',
        'MovshareResolver_priority'            : '100',
        'MovshareResolver_enabled'             : 'true',
        'Mp4EdgeResolver_priority'             : '100',
        'Mp4EdgeResolver_enabled'              : 'true',
        'Mp4streamResolver_priority'           : '100',
        'Mp4streamResolver_enabled'            : 'true',
        'Mp4uploadResolver_priority'           : '100',
        'Mp4uploadResolver_enabled'            : 'true',
        'NosvideoResolver_priority'            : '100',
        'NosvideoResolver_enabled'             : 'true',
        'NovamovResolver_priority'             : '100',
        'NovamovResolver_enabled'              : 'true',
        'NowvideoResolver_priority'            : '100',
        'NowvideoResolver_enabled'             : 'true',
        'OKResolver_priority'                  : '100',
        'OKResolver_enabled'                   : 'true',
        'OKResolver_auto_pick'                 : 'false',
        'OpenLoadResolver_priority'            : '100',
        'OpenLoadResolver_enabled'             : 'true',
        'Play44Resolver_priority'              : '100',
        'Play44Resolver_enabled'               : 'true',
        'PlayHDResolver_priority'              : '100',
        'PlayHDResolver_enabled'               : 'true',
        'PlaywireResolver_priority'            : '100',
        'PlaywireResolver_enabled'             : 'true',
        'PrimeshareResolver_priority'          : '100',
        'PrimeshareResolver_enabled'           : 'true',
        'PromptfileResolver_priority'          : '100',
        'PromptfileResolver_enabled'           : 'true',
        'PureVidResolver_priority'             : '100',
        'PureVidResolver_enabled'              : 'true',
        'PureVidResolver_login'                : 'false',
        'PureVidResolver_username'             : '',
        'PureVidResolver_password'             : '',
        'PureVidResolver_quality'              : 'Maximum',
        'Shared2meResolver_priority'           : '100',
        'Shared2meResolver_enabled'            : 'true',
        'SharedsxResolver_priority'            : '100',
        'SharedsxResolver_enabled'             : 'true',
        'SharerepoResolver_priority'           : '100',
        'SharerepoResolver_enabled'            : 'true',
        'SharesixResolver_priority'            : '100',
        'SharesixResolver_enabled'             : 'true',
        'SpeedPlayResolver_priority'           : '100',
        'SpeedPlayResolver_enabled'            : 'true',
        'SpeedVideoResolver_priority'          : '100',
        'SpeedVideoResolver_enabled'           : 'true',
        'StagevuResolver_priority'             : '100',
        'StagevuResolver_enabled'              : 'true',
        'StreamcloudResolver_priority'         : '100',
        'StreamcloudResolver_enabled'          : 'true',
        'StreamintoResolver_priority'          : '100',
        'StreamintoResolver_enabled'           : 'true',
        'TeramixerResolver_priority'           : '100',
        'TeramixerResolver_enabled'            : 'true',
        'TheVideoResolver_priority'            : '100',
        'TheVideoResolver_enabled'             : 'true',
        'VideoBeeResolver_priority'            : '100',
        'VideoBeeResolver_enabled'             : 'true',
        'TrollVidResolver_priority'            : '100',
        'TrollVidResolver_enabled'             : 'true',
        'TunePkResolver_priority'              : '100',
        'TunePkResolver_enabled'               : 'true',
        'TunePkResolver_quality'               : '0',
        'TusfilesResolver_priority'            : '100',
        'TusfilesResolver_enabled'             : 'true',
        'Up2StreamResolver_priority'           : '100',
        'Up2StreamResolver_enabled'            : 'true',
        'UploadAfResolver_priority'            : '100',
        'UploadAfResolver_enabled'             : 'true',
        'UploadcResolver_priority'             : '100',
        'UploadcResolver_enabled'              : 'true',
        'UploadXResolver_priority'             : '100',
        'UploadXResolver_enabled'              : 'true',
        'UpToBoxResolver_priority'             : '100',
        'UpToBoxResolver_enabled'              : 'true',
        'UsersCloudResolver_priority'          : '100',
        'UsersCloudResolver_enabled'           : 'true',
        'UsersFilesResolver_priority'          : '100',
        'UsersFilesResolver_enabled'           : 'true',
        'VeeHDResolver_priority'               : '100',
        'VeeHDResolver_enabled'                : 'true',
        'VeeHDResolver_login'                  : 'false',
        'VeeHDResolver_username'               : '',
        'VeeHDResolver_password'               : '',
        'VeohResolver_priority'                : '100',
        'VeohResolver_enabled'                 : 'true',
        'VidggResolver_priority'               : '100',
        'VidggResolver_enabled'                : 'true',
        'VidMeResolver_priority'               : '100',
        'VidMeResolver_enabled'                : 'true',
        'VidbullResolver_priority'             : '100',
        'VidbullResolver_enabled'              : 'true',
        'VidCrazyResolver_priority'            : '100',
        'VidCrazyResolver_enabled'             : 'true',
        'VideoHutResolver_priority'            : '100',
        'VideoHutResolver_enabled'             : 'true',
        'VideoMegaResolver_priority'           : '100',
        'VideoMegaResolver_enabled'            : 'true',
        'VideoRajResolver_priority'            : '100',
        'VideoRajResolver_enabled'             : 'true',
        'VideoTTResolver_priority'             : '100',
        'VideoTTResolver_enabled'              : 'true',
        'VideoTTResolver_quality'              : '0',
        'VideoweedResolver_priority'           : '100',
        'VideoweedResolver_enabled'            : 'true',
        'VideowoodResolver_priority'           : '100',
        'VideowoodResolver_enabled'            : 'true',
        'VideoZooResolver_priority'            : '100',
        'VideoZooResolver_enabled'             : 'true',
        'VidioResolver_priority'               : '100',
        'VidioResolver_enabled'                : 'true',
        'VidSpotResolver_priority'             : '100',
        'VidSpotResolver_enabled'              : 'true',
        'VidtoResolver_priority'               : '100',
        'VidtoResolver_enabled'                : 'true',
        'VidUpResolver_priority'               : '100',
        'VidUpResolver_enabled'                : 'true',
        'VidziResolver_priority'               : '100',
        'VidziResolver_enabled'                : 'true',
        'VimeoResolver_priority'               : '100',
        'VimeoResolver_enabled'                : 'true',
        'VimeoResolver_quality'                : '0',
        'VivosxResolver_priority'              : '100',
        'VivosxResolver_enabled'               : 'true',
        'VKResolver_priority'                  : '100',
        'VKResolver_enabled'                   : 'true',
        'VKResolver_auto_pick'                 : 'false',
        'VKPassResolver_priority'              : '100',
        'VKPassResolver_enabled'               : 'true',
        'VKPassResolver_auto_pick'             : 'false',
        'VodlockerResolver_priority'           : '100',
        'VodlockerResolver_enabled'            : 'true',
        'VshareResolver_priority'              : '100',
        'VshareResolver_enabled'               : 'true',
        'VshareEuResolver_priority'            : '100',
        'VshareEuResolver_enabled'             : 'true',
        'WatchVideoResolver_priority'          : '100',
        'WatchVideoResolver_enabled'           : 'true',
        'XvidstageResolver_priority'           : '100',
        'XvidstageResolver_enabled'            : 'true',
        'YourUploadResolver_priority'          : '100',
        'YourUploadResolver_enabled'           : 'true',
        'YoutubeResolver_priority'             : '100',
        'YoutubeResolver_enabled'              : 'true',
        'YouWatchResolver_priority'            : '100',
        'YouWatchResolver_enabled'             : 'true',
        'ZettahostResolver_priority'           : '100',
        'ZettahostResolver_enabled'            : 'true',
        'ZstreamResolver_priority'             : '100',
        'ZstreamResolver_enabled'              : 'true'
    }
}
strings = {
    'plugin.video.exodus': {
        30001: 'Movies',
        30002: 'TV Shows',
        30003: 'Channels',
        30004: 'My Lists',
        30005: 'Latest Movies',
        30006: 'Latest Episodes',
        30007: 'TV Calendar',
        30008: 'Tools',
        30009: 'Search',
        30010: 'Downloads',
        30021: 'Genres',
        30022: 'Year',
        30023: 'People',
        30024: 'Certificates',
        30025: 'Featured',
        30026: 'People Watching',
        30027: 'Most Popular',
        30028: 'Most Voted',
        30029: 'Box Office',
        30030: 'Oscar Winners',
        30031: 'In Theaters',
        30032: 'Latest Movies',
        30033: 'My Lists',
        30034: 'People Search',
        30035: 'Search',
        30036: 'Collection',
        30037: 'Watchlist',
        30038: 'Movie Lists',
        30039: 'History',
        30051: 'Genres',
        30052: 'Year',
        30053: 'Networks',
        30054: 'People Watching',
        30055: 'Most Popular',
        30056: 'Airing today',
        30057: 'Returning TV Shows',
        30058: 'New TV Shows',
        30059: 'Highly Rated',
        30060: 'Most Voted',
        30061: 'TV Calendar',
        30062: 'Latest Episodes',
        30063: 'My Lists',
        30065: 'People Search',
        30066: 'Search',
        30067: 'Collection',
        30068: 'Watchlist',
        30069: 'Progress',
        30070: 'Featured',
        30071: 'TV Show Lists',
        30072: 'Episode Lists',
        30073: 'History',
        30081: 'No Trakt or IMDb account found.',
        30082: 'Trakt indicators are disabled by default.',
        30083: 'In order to use them enable them in settings.',
        30084: '[B]TRAKT[/B] : Collection',
        30085: '[B]TRAKT[/B] : TV Collection',
        30086: '[B]TRAKT[/B] : Watchlist',
        30087: '[B]TRAKT[/B] : TV Watchlist',
        30088: '[B]IMDB[/B] : Watchlist',
        30089: '[B]IMDB[/B] : TV Watchlist',
        30090: '[B]TRAKT[/B] : Featured',
        30091: '[B]TRAKT[/B] : TV Featured',
        30092: '[B]TRAKT[/B] : History',
        30093: '[B]TRAKT[/B] : TV History',
        30094: '[B]TRAKT[/B] : Progress',
        30095: '[B]TRAKT[/B] : Episodes',
        30096: 'Movie Lists',
        30097: 'TV Show Lists',
        30098: 'Episode Lists',
        30111: '[B]SETTINGS[/B] : General',
        30112: '[B]SETTINGS[/B] : Accounts',
        30113: '[B]SETTINGS[/B] : Playback',
        30114: '[B]SETTINGS[/B] : Subtitles',
        30115: '[B]SETTINGS[/B] : Providers',
        30119: '[B]EXODUS[/B] : Clear providers...',
        30120: '[B]EXODUS[/B] : Clear cache...',
        30122: '[B]EXODUS[/B] : Downloads',
        30141: 'Movies',
        30142: 'TV Shows',
        30151: 'Movies',
        30152: 'TV Shows',
        30153: 'People (Movies)',
        30154: 'People (TV)',
        30155: 'Queue item',
        30201: 'Search',
        30202: 'Queue item',
        30203: 'Auto-play',
        30204: 'Play using...',
        30205: 'Movie information',
        30206: 'Mark as watched',
        30207: 'Mark as unwatched',
        30208: 'Trakt Manager',
        30209: 'Add to favourites',
        30210: 'Remove from favourites',
        30212: 'Set Movies view',
        30213: '[I]Next Page[/I]',
        30214: 'Movie trailer',
        30231: 'Search',
        30232: 'Queue item',
        30233: 'TV show information',
        30234: 'Mark as watched',
        30235: 'Mark as unwatched',
        30236: 'Trakt Manager',
        30237: 'Add to favourites',
        30238: 'Remove from favourites',
        30240: 'Set TV Shows view',
        30241: '[I]Next Page[/I]',
        30242: 'TV show trailer',
        30261: 'Queue item',
        30262: 'TV show information',
        30263: 'Mark as watched',
        30264: 'Mark as unwatched',
        30265: 'Trakt Manager',
        30266: 'Add to favourites',
        30267: 'Remove from favourites',
        30268: 'TV show trailer',
        30269: 'Set Seasons view',
        30270: 'Auto-play',
        30271: 'Play using...',
        30272: 'Episode information',
        30273: 'Set Episodes view',
        30274: 'Browse Seasons',
        30275: 'Season',
        30291: 'Auto-play',
        30292: 'Play using...',
        30293: 'Information',
        30294: 'Refresh',
        30295: 'Add-on settings',
        30296: 'Now playing...',
        30297: 'Trailer',
        30401: 'Are you sure?',
        30402: 'Process Complete',
        30411: 'A RealDebrid account already exists',
        30413: 'Do you want to reset?',
        30414: 'Yes',
        30415: 'No',
        30416: '1) Visit : ',
        30417: '2) When prompted enter : ',
        30451: 'Getting information',
        30461: 'Resume from',
        30462: 'Start from beginning',
        30463: 'Resume',
        30464: 'Loaded in',
        30465: 'seconds',
        30471: 'Trakt Manager',
        30472: 'Add to Collection',
        30473: 'Remove from Collection',
        30474: 'Add to Watchlist',
        30475: 'Remove from Watchlist',
        30476: 'Add to new List',
        30477: 'Add to',
        30478: 'Remove from',
        30479: 'A Trakt account already exists',
        30481: 'Do you want to reset?',
        30482: 'Yes',
        30483: 'No',
        30491: 'This View is now Default',
        30501: 'No stream available',
        30502: 'Movie information',
        30503: 'Episode information',
        30504: 'Queue item',
        30505: 'Download item',
        30506: 'Refresh providers',
        30507: 'Add-on settings',
        30508: 'Now playing...',
        30509: 'Auto-play',
        30510: 'Are you sure?',
        30511: 'Process Complete',
        30512: 'Time elapsed',
        30513: 'seconds',
        30514: 'Remaining providers',
        30515: 'Loading streams',
        30516: 'Movie trailer',
        30517: 'TV show trailer',
        30518: 'Playback outside Exodus is not allowed',
        30521: 'Monday',
        30522: 'Tuesday',
        30523: 'Wednesday',
        30524: 'Thursday',
        30525: 'Friday',
        30526: 'Saturday',
        30527: 'Sunday',
        30528: 'January',
        30529: 'February',
        30530: 'March',
        30531: 'April',
        30532: 'May',
        30533: 'June',
        30534: 'July',
        30535: 'August',
        30536: 'September',
        30537: 'October',
        30538: 'November',
        30539: 'December',
        30800: 'General',
        30801: 'Appearance',
        30802: 'Enable Fanart',
        30803: 'Info Language',
        30804: 'Providers Timeout',
        30805: 'Main menu',
        30806: 'Latest Movies',
        30807: 'Disabled',
        30808: 'Featured',
        30809: 'People Watching',
        30810: 'Most Popular',
        30811: 'In Theaters',
        30812: 'Latest Episodes',
        30813: 'Disabled',
        30814: 'Episodes',
        30815: 'Trakt Progress',
        30816: 'Trakt Episodes',
        30817: 'TV Calendar',
        30818: 'Disabled',
        30819: 'Enabled',
        30820: 'Indicators',
        30821: 'Local',
        30822: 'Trakt',
        30823: 'My Lists',
        30824: 'Disabled',
        30825: 'Enabled',
        30826: 'Sub menu',
        30827: 'Classic',
        30828: 'Flatten TV show seasons',
        30830: 'Playback',
        30831: 'Max Quality',
        30832: 'Host selection',
        30833: 'Dialog',
        30834: 'Directory',
        30835: 'File Hosting Filters',
        30836: 'Hosters with captchas',
        30837: 'Sort by Provider',
        30839: 'Auto-play',
        30840: 'Auto-play',
        30842: 'Force SD playback in Auto-play',
        30843: 'When playback starts...',
        30844: 'Resume Playback',
        30845: 'Playback Info',
        30846: 'Progress Dialog',
        30847: 'Safe',
        30848: 'Unsafe',
        30860: 'Providers',
        30910: 'Accounts',
        30911: 'User',
        30912: 'Email',
        30913: 'Password',
        30914: 'Authorization...',
        30940: 'Subtitles',
        30941: 'Subtitles could be unavailable or out of sync.',
        30942: 'In that case use your own subtitles.',
        30943: 'Enable subtitles',
        30944: 'Convert subtitles to UTF-8',
        30945: 'Primary Language',
        30946: 'Secondary Language',
        30950: 'Downloads',
        30951: 'Movies',
        30952: 'TV',
        30953: 'Enable downloads',
        30954: 'Downloading features are disabled by default.',
        30955: 'Set up your download folders in order to enable them.'
    }
}
